package com.example.utils

import android.content.ContentValues
import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import com.example.data.LedgerGroup
import com.example.data.TransactionEntry
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfExporter {

    suspend fun exportGroupHistoryToPdf(
        context: Context,
        group: LedgerGroup,
        transactions: List<TransactionEntry>,
        currencySymbol: String,
        includeWatermark: Boolean
    ): String? = withContext(Dispatchers.IO) {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size
        var page = document.startPage(pageInfo)
        var canvas = page.canvas

        val titlePaint = Paint().apply {
            color = Color.BLACK
            textSize = 24f
            isFakeBoldText = true
            textAlign = Paint.Align.LEFT
        }

        val subHeaderPaint = Paint().apply {
            color = Color.DKGRAY
            textSize = 14f
            textAlign = Paint.Align.LEFT
        }

        val headerBgPaint = Paint().apply {
            color = Color.LTGRAY
        }

        val columnHeaderPaint = Paint().apply {
            color = Color.BLACK
            textSize = 14f
            isFakeBoldText = true
            textAlign = Paint.Align.LEFT
        }

        val textPaint = Paint().apply {
            color = Color.BLACK
            textSize = 12f
            textAlign = Paint.Align.LEFT
        }

        val positiveAmountPaint = Paint().apply {
            color = Color.rgb(46, 125, 50) // Green
            textSize = 12f
            textAlign = Paint.Align.LEFT
            isFakeBoldText = true
        }

        val negativeAmountPaint = Paint().apply {
            color = Color.rgb(198, 40, 40) // Red
            textSize = 12f
            textAlign = Paint.Align.LEFT
            isFakeBoldText = true
        }

        val linePaint = Paint().apply {
            color = Color.LTGRAY
            strokeWidth = 1f
        }

        val watermarkPaint = Paint().apply {
            color = Color.GRAY
            textSize = 10f
            textAlign = Paint.Align.CENTER
        }

        val margin = 50f
        var yPosition = 80f
        val pageHeight = 842f
        val maxPageHeight = pageHeight - 100f // leave bottom margin

        // Draw Title
        canvas.drawText(group.name, margin, yPosition, titlePaint)
        yPosition += 30f

        val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
        val exportDate = dateFormat.format(Date())
        canvas.drawText("Exported on: $exportDate", margin, yPosition, subHeaderPaint)
        yPosition += 40f

        // Draw Table Header
        val col1X = margin
        val col2X = margin + 150f
        val col3X = margin + 300f

        canvas.drawRect(margin, yPosition - 20f, 595f - margin, yPosition + 10f, headerBgPaint)
        canvas.drawText("Date/Time", col1X, yPosition, columnHeaderPaint)
        canvas.drawText("Amount", col2X, yPosition, columnHeaderPaint)
        canvas.drawText("Note", col3X, yPosition, columnHeaderPaint)
        
        yPosition += 30f

        var totalIncome = 0.0
        var totalExpense = 0.0

        for (tx in transactions) {
            if (yPosition > maxPageHeight) {
                if (includeWatermark) {
                    canvas.drawText("Generated by sri App", 595f / 2, pageHeight - 30f, watermarkPaint)
                }
                document.finishPage(page)
                page = document.startPage(pageInfo)
                canvas = page.canvas
                yPosition = 80f
                
                // Draw Table Header on new page
                canvas.drawRect(margin, yPosition - 20f, 595f - margin, yPosition + 10f, headerBgPaint)
                canvas.drawText("Date/Time", col1X, yPosition, columnHeaderPaint)
                canvas.drawText("Amount", col2X, yPosition, columnHeaderPaint)
                canvas.drawText("Note", col3X, yPosition, columnHeaderPaint)
                yPosition += 30f
            }

            if (tx.amount >= 0) totalIncome += tx.amount
            else totalExpense += Math.abs(tx.amount)

            val dateStr = dateFormat.format(Date(tx.timestamp))
            val isInteger = tx.amount % 1.0 == 0.0
            val amountStr = if (isInteger) tx.amount.toLong().toString() else String.format("%.2f", tx.amount)
            val displayAmount = if (tx.amount >= 0) "+$currencySymbol$amountStr" else "-$currencySymbol${amountStr.replace("-", "")}"

            val paint = if (tx.amount >= 0) positiveAmountPaint else negativeAmountPaint

            canvas.drawText(dateStr, col1X, yPosition, textPaint)
            canvas.drawText(displayAmount, col2X, yPosition, paint)
            
            // Handle long notes (simple truncate for now)
            var noteText = tx.label.ifEmpty { "Entry" }
            if (noteText.length > 35) noteText = noteText.take(32) + "..."
            canvas.drawText(noteText, col3X, yPosition, textPaint)

            yPosition += 10f
            canvas.drawLine(margin, yPosition, 595f - margin, yPosition, linePaint)
            yPosition += 20f
        }

        // Summary Section
        if (yPosition > maxPageHeight - 100f) {
            if (includeWatermark) {
                canvas.drawText("Generated by sri App", 595f / 2, pageHeight - 30f, watermarkPaint)
            }
            document.finishPage(page)
            page = document.startPage(pageInfo)
            canvas = page.canvas
            yPosition = 80f
        }

        yPosition += 20f
        canvas.drawText("Summary", margin, yPosition, titlePaint)
        yPosition += 30f

        val formatAmount: (Double) -> String = { amt ->
            val isInt = amt % 1.0 == 0.0
            if (isInt) amt.toLong().toString() else String.format("%.2f", amt)
        }

        canvas.drawText("Total Income:", margin, yPosition, subHeaderPaint)
        canvas.drawText("+$currencySymbol${formatAmount(totalIncome)}", margin + 150f, yPosition, positiveAmountPaint)
        yPosition += 25f

        canvas.drawText("Total Expense:", margin, yPosition, subHeaderPaint)
        canvas.drawText("-$currencySymbol${formatAmount(totalExpense)}", margin + 150f, yPosition, negativeAmountPaint)
        yPosition += 25f

        val netBalance = totalIncome - totalExpense
        canvas.drawText("Net Balance:", margin, yPosition, columnHeaderPaint)
        val netPaint = if (netBalance >= 0) positiveAmountPaint else negativeAmountPaint
        val netPrefix = if (netBalance >= 0) "+" else "-"
        canvas.drawText("$netPrefix$currencySymbol${formatAmount(Math.abs(netBalance))}", margin + 150f, yPosition, netPaint)

        if (includeWatermark) {
            canvas.drawText("Generated by sri App", 595f / 2, pageHeight - 30f, watermarkPaint)
        }

        document.finishPage(page)

        val safeGroupName = group.name.replace(Regex("[^a-zA-Z0-9_-]"), "_")
        val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
        val fileName = "${safeGroupName}_$timestamp.pdf"
        var filePath: String? = null

        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                val resolver = context.contentResolver
                val contentValues = ContentValues().apply {
                    put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                    put(MediaStore.MediaColumns.MIME_TYPE, "application/pdf")
                    put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
                }
                val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                if (uri != null) {
                    resolver.openOutputStream(uri)?.use { outputStream ->
                        document.writeTo(outputStream)
                    }
                    // For Android 10+, the real path might not be readable, but we can return URI string
                    filePath = uri.toString()
                }
            } else {
                val downloadsDir = context.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS)
                if (downloadsDir != null && !downloadsDir.exists()) downloadsDir.mkdirs()
                val file = File(downloadsDir, fileName)
                FileOutputStream(file).use { outputStream ->
                    document.writeTo(outputStream)
                }
                filePath = file.absolutePath
            }
        } catch (e: Exception) {
            e.printStackTrace()
            return@withContext null
        } finally {
            document.close()
        }

        return@withContext filePath
    }
}
